"""Add time tracking and recurring features

Revision ID: 2b86659811f5
Revises: dc0ebccc7ce6
Create Date: 2025-05-28 23:23:03.083081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b86659811f5'
down_revision: Union[str, None] = 'dc0ebccc7ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
