"""Add recurring, contact info, deadlines, and priority

Revision ID: dc0ebccc7ce6
Revises: 5145c5640ed4
Create Date: 2025-05-28 22:24:33.964956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0ebccc7ce6'
down_revision: Union[str, None] = '5145c5640ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('recurrence_interval', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_interval', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('priority_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority_level')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'recurrence_interval')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('projects', 'recurrence_interval')
    op.drop_column('projects', 'is_recurring')
    op.drop_column('clients', 'notes')
    op.drop_column('clients', 'phone_number')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
